### ISSUE TITLE
Filter (or discard) notices based on user agent

### ISSUE THREAD

**Issue by danielneis** [emgiezet/errbitPHP#22]
Hello,

I've first suggested it in errbit/errbit#1081 , but the author suggested it sould be done on the client library, not on the Errbit server. The official AirBrake API already expects that, as noted in https://github.com/errbit/errbit/issues/1081#issuecomment-209599417

Also, we've found that there is a "shouldNotify" function that could be extended with this filter:
https://github.com/emgiezet/errbitPHP/blob/master/src/Errbit/Errbit.php#L165

If you prefer, I can do the necessary changes and open a pull request. What do you say?

Kind regards,
Daniel

**Comment by emgiezet** [comment]
Hi!

Thanks for contribution! I will merge it today with the new tag 1.1.1

Cheers!
Max

**Comment by danielneis** [comment]
Ok, thank you!
I am using it on two live sites and it is working as expected.

Kind regards,
Daniel
